### ISSUE TITLE
Result for the tutorials 

### ISSUE THREAD

**Issue by Shubhangi1397** [abeebyekeen/CHAPERONg#1]
Hello, 
I was planning to go through the Chaperong tutorials. Is there a result document so that I can tally my results to what should be expected out of the tutorials? 
Best regards,
Shubhangi

**Comment by abeebyekeen** [comment]
Hi,

All [the tutorials](https://abeebyekeen.com/chaperong-online-tutorials/) contain links to download the input files used and the expected output files/plots are shown. For [Tutorial 1](https://abeebyekeen.com/chaperong-tutorial-1-ubiquitin-in-water/) where the trajectory files are not that huge, the entire directory (including all input and output files) is provided for download. For the other tutorials, the trajectory files are huge, so only the input files and the results (generated plots) are provided. Generally, if you follow the tutorials, and there are no errors thrown, and you see the plots produced, then it usually means everything went well. I may consider bundling the entire directory for each of the others and uploading them on zenodo later.

I hope this helps.
