### ISSUE TITLE
Protein-peptide complex simulation

### ISSUE THREAD

**Issue by Daniyalprime** [abeebyekeen/CHAPERONg#2]
Hi,
I am currently planning to conduct an MD simulation on a protein-peptide complex and am interested in utilizing CHAPERONg for this purpose, including the post-trajectory analysis with MM/PBSA. I would appreciate guidance on how to effectively use CHAPERONg for a protein-peptide complex simulation.

Best regards,
Daniyal

**Comment by abeebyekeen** [comment]
Hi. For protein-protein (and protein-peptide) complex simulation, you do not need to do anything special. You typically just follow the same workflow as a single-chain protein simulation.
