### ISSUE TITLE
Version has expired , while installation

### ISSUE THREAD

**Issue by Arikite-netizen** [abeebyekeen/CHAPERONg#4]
I was installing the CHAPERONEg package as instructed in the READ.me file. However, while running the installation script. I got this error, please help with why has the version expired.

The error is given below :
chmod +x install_CHAPERONg.sh && ./install_CHAPERONg.sh
./install_CHAPERONg.sh: has expired!
Sorry, this experimental version of CHAPERONg has expired! Contact Abeeb A. Yekeen (abeeb.yekeen@hotmail.com) or visit https://github.com/abeebyekeen/CHAPERONg for the production release of the code. Thanks...

**Comment by abeebyekeen** [comment]
> I was installing the CHAPERONEg package as instructed in the READ.me file. However, while running the installation script. I got this error, please help with why has the version expired.
> 
> 
> 
> The error is given below :
> 
> chmod +x install_CHAPERONg.sh && ./install_CHAPERONg.sh
> 
> ./install_CHAPERONg.sh: has expired!
> 
> Sorry, this experimental version of CHAPERONg has expired! Contact Abeeb A. Yekeen (abeeb.yekeen@hotmail.com) or visit https://github.com/abeebyekeen/CHAPERONg for the production release of the code. Thanks...
> 
> 

When did you download the code?

**Comment by abeebyekeen** [comment]
@Arikite-netizen Download the current version of the code and install
